version: '3'

services:
#  mongo:
#    container_name: mongodb
#    image: mongo
#    environment:
#      - MONGO_INITDB_DATABASE=test
#    volumes:
#      - ./database/mongo:/data/db
#    ports:
#      - "27017:27017"
#    restart: on-failure
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"